name: Deploy to DEV

on:
  push:
    branches:
      - working

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 72.60.218.170
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
         script: |
          export PATH=$PATH:/root/.nvm/versions/node/v20.20.2/bin
          cd /root/Hawksyn/Hawksyn-Backend
          git pull origin working
          npm install
          npm run migrate:up
          pm2 restart hawksyn-backend
